apiVersion: v1
kind: Namespace
metadata:
  name: dojo-services-build
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dojo-services-build
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
