// Package lima implements provider.Provider on top of limactl.
//
// Guest OS pin lives here: Lima's own _images/ubuntu-24.04 template is used as
// the base so image URLs and digests stay maintained upstream.
package lima

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/gustavfredrikson/cka-dojo/internal/provider"
	"github.com/gustavfredrikson/cka-dojo/internal/ui"
)

// Provider drives limactl.
type Provider struct {
	// Binary is the limactl executable; empty means look it up on PATH.
	Binary string
}

// New returns a Lima provider.
func New() *Provider { return &Provider{} }

// Name implements provider.Provider.
func (p *Provider) Name() string { return "lima" }

func (p *Provider) bin() string {
	if p.Binary != "" {
		return p.Binary
	}
	return "limactl"
}

// Available reports whether limactl is installed.
func (p *Provider) Available() error {
	if _, err := exec.LookPath(p.bin()); err != nil {
		return fmt.Errorf("limactl not found on PATH: install it with `brew install lima`")
	}
	return nil
}

// Version returns the limactl version string.
func (p *Provider) Version(ctx context.Context) (string, error) {
	out, _, err := p.run(ctx, nil, "--version")
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(out), "limactl version ")), nil
}

func (p *Provider) run(ctx context.Context, stdin *strings.Reader, args ...string) (string, string, error) {
	cmd := exec.CommandContext(ctx, p.bin(), args...)
	if stdin != nil {
		cmd.Stdin = stdin
	}
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	ui.Detail("limactl %s", strings.Join(args, " "))
	err := cmd.Run()
	if stderr.Len() > 0 {
		ui.Detail("stderr: %s", strings.TrimSpace(stderr.String()))
	}
	return stdout.String(), stderr.String(), err
}

type instance struct {
	Name   string `json:"name"`
	Status string `json:"status"`
	Dir    string `json:"dir"`
}

func (p *Provider) instances(ctx context.Context) ([]instance, error) {
	out, stderr, err := p.run(ctx, nil, "list", "--format", "json")
	if err != nil {
		return nil, fmt.Errorf("limactl list: %w: %s", err, lastLines(stderr, 4))
	}
	// limactl emits one JSON object per instance, not a JSON array.
	var list []instance
	dec := json.NewDecoder(strings.NewReader(out))
	for {
		var in instance
		if err := dec.Decode(&in); err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return nil, fmt.Errorf("parse limactl list output: %w", err)
		}
		list = append(list, in)
	}
	return list, nil
}

func mapStatus(s string) provider.Status {
	switch strings.ToLower(s) {
	case "running":
		return provider.StatusRunning
	case "stopped":
		return provider.StatusStopped
	case "broken":
		return provider.StatusBroken
	case "":
		return provider.StatusUnknown
	default:
		return provider.StatusUnknown
	}
}

// Status implements provider.Provider.
func (p *Provider) Status(ctx context.Context, name string) (provider.Status, error) {
	list, err := p.instances(ctx)
	if err != nil {
		return provider.StatusUnknown, err
	}
	for _, in := range list {
		if in.Name == name {
			return mapStatus(in.Status), nil
		}
	}
	return provider.StatusMissing, nil
}

// List implements provider.Provider.
func (p *Provider) List(ctx context.Context, prefix string) ([]provider.NodeInfo, error) {
	list, err := p.instances(ctx)
	if err != nil {
		return nil, err
	}
	var out []provider.NodeInfo
	for _, in := range list {
		if prefix != "" && !strings.HasPrefix(in.Name, prefix) {
			continue
		}
		out = append(out, provider.NodeInfo{Name: in.Name, Status: mapStatus(in.Status), Dir: in.Dir})
	}
	return out, nil
}

// instanceYAML renders the Lima instance definition for a node.
//
// Notes that matter:
//   - no mounts: the training repo must never be visible inside a guest.
//   - containerd disabled: we install and own containerd ourselves, because
//     labs need to break it.
//   - user-v2 network: gives VM-to-VM connectivity on 192.168.104.0/24.
func instanceYAML(spec provider.NodeSpec) string {
	var b strings.Builder
	b.WriteString("# Generated by dojo. Edits are overwritten on recreate.\n")
	b.WriteString("minimumLimaVersion: 2.0.0\n")
	b.WriteString("base:\n- template:_images/ubuntu-24.04\n")
	b.WriteString("vmType: vz\n")
	b.WriteString("rosetta:\n  enabled: false\n  binfmt: false\n")
	fmt.Fprintf(&b, "cpus: %d\n", spec.CPUs)
	fmt.Fprintf(&b, "memory: %q\n", spec.Memory)
	fmt.Fprintf(&b, "disk: %q\n", spec.Disk)
	b.WriteString("mounts: []\n")
	b.WriteString("containerd:\n  system: false\n  user: false\n")
	if spec.Network != "" {
		fmt.Fprintf(&b, "networks:\n- lima: %s\n", spec.Network)
	}
	b.WriteString("ssh:\n  loadDotSSHPubKeys: false\n")
	if spec.Hostname != "" {
		// Set before anything else runs: Kubernetes node names come from the
		// hostname, so it has to be correct on first boot.
		fmt.Fprintf(&b, `provision:
- mode: system
  script: |
    #!/bin/bash
    set -eu
    hostnamectl set-hostname %s
    sed -i "/^127.0.1.1/d" /etc/hosts
    echo "127.0.1.1 %s" >> /etc/hosts
`, spec.Hostname, spec.Hostname)
	}
	return b.String()
}

// EnsureNode implements provider.Provider.
func (p *Provider) EnsureNode(ctx context.Context, spec provider.NodeSpec) error {
	st, err := p.Status(ctx, spec.Name)
	if err != nil {
		return err
	}
	switch st {
	case provider.StatusRunning:
		return nil
	case provider.StatusStopped:
		return p.StartNode(ctx, spec.Name)
	case provider.StatusBroken:
		return fmt.Errorf("lima instance %s is broken; run `dojo env destroy` and try again", spec.Name)
	}

	dir, err := os.MkdirTemp("", "dojo-lima-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(dir)
	yamlPath := filepath.Join(dir, spec.Name+".yaml")
	if err := os.WriteFile(yamlPath, []byte(instanceYAML(spec)), 0o644); err != nil {
		return err
	}
	ui.Detail("creating lima instance %s", spec.Name)
	_, stderr, err := p.run(ctx, nil, "start", "--tty=false", "--name="+spec.Name, yamlPath)
	if err != nil {
		return fmt.Errorf("create %s: %w: %s", spec.Name, err, lastLines(stderr, 8))
	}
	return nil
}

// StartNode implements provider.Provider.
func (p *Provider) StartNode(ctx context.Context, name string) error {
	_, stderr, err := p.run(ctx, nil, "start", "--tty=false", name)
	if err != nil {
		return fmt.Errorf("start %s: %w: %s", name, err, lastLines(stderr, 8))
	}
	return nil
}

// StopNode implements provider.Provider.
func (p *Provider) StopNode(ctx context.Context, name string) error {
	st, err := p.Status(ctx, name)
	if err != nil || st != provider.StatusRunning {
		return err
	}
	_, stderr, err := p.run(ctx, nil, "stop", name)
	if err != nil {
		return fmt.Errorf("stop %s: %w: %s", name, err, lastLines(stderr, 8))
	}
	return nil
}

// DestroyNode implements provider.Provider.
func (p *Provider) DestroyNode(ctx context.Context, name string) error {
	st, err := p.Status(ctx, name)
	if err != nil {
		return err
	}
	if st == provider.StatusMissing {
		return nil
	}
	_, stderr, err := p.run(ctx, nil, "delete", "--force", name)
	if err != nil {
		return fmt.Errorf("delete %s: %w: %s", name, err, lastLines(stderr, 8))
	}
	return nil
}

// Exec implements provider.Provider.
//
// The script travels on stdin rather than in argv: that removes every quoting
// question about how limactl and ssh reassemble a command line.
func (p *Provider) Exec(ctx context.Context, name string, opts provider.ExecOptions) (provider.ExecResult, error) {
	args := []string{"shell", name, "--"}
	switch opts.User {
	case "", "default":
		args = append(args, "bash", "-s")
	case "root":
		args = append(args, "sudo", "bash", "-s")
	default:
		args = append(args, "sudo", "-H", "-u", opts.User, "bash", "-s")
	}
	cmd := exec.CommandContext(ctx, p.bin(), args...)
	cmd.Stdin = strings.NewReader(opts.Script)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	ui.Detail("exec on %s (user=%q): %s", name, opts.User, firstLine(opts.Script))
	err := cmd.Run()
	res := provider.ExecResult{Stdout: stdout.String(), Stderr: stderr.String()}
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			res.ExitCode = ee.ExitCode()
			ui.Detail("exit %d on %s: %s", res.ExitCode, name, lastLines(res.Stderr, 5))
			return res, &provider.ExitError{Node: name, Result: res}
		}
		return res, err
	}
	return res, nil
}

// WriteFile implements provider.Provider.
func (p *Provider) WriteFile(ctx context.Context, name, path string, content []byte, mode fs.FileMode) error {
	enc := base64.StdEncoding.EncodeToString(content)
	var b strings.Builder
	b.WriteString("set -euo pipefail\n")
	fmt.Fprintf(&b, "mkdir -p %q\n", filepath.Dir(path))
	fmt.Fprintf(&b, "base64 -d > %q <<'DOJO_B64_EOF'\n", path)
	// Wrap so the heredoc line length stays sane for very large payloads.
	for i := 0; i < len(enc); i += 76 {
		end := i + 76
		if end > len(enc) {
			end = len(enc)
		}
		b.WriteString(enc[i:end])
		b.WriteString("\n")
	}
	b.WriteString("DOJO_B64_EOF\n")
	fmt.Fprintf(&b, "chmod %04o %q\n", mode.Perm(), path)
	_, err := p.Exec(ctx, name, provider.ExecOptions{Script: b.String(), User: "root"})
	return err
}

// ReadFile implements provider.Provider.
func (p *Provider) ReadFile(ctx context.Context, name, path string) ([]byte, error) {
	script := fmt.Sprintf("set -euo pipefail\nbase64 < %q\n", path)
	res, err := p.Exec(ctx, name, provider.ExecOptions{Script: script, User: "root"})
	if err != nil {
		return nil, err
	}
	clean := strings.Join(strings.Fields(res.Stdout), "")
	return base64.StdEncoding.DecodeString(clean)
}

// Shell implements provider.Provider.
func (p *Provider) Shell(ctx context.Context, name, user string, args []string) error {
	limaArgs := []string{"shell", name, "--"}
	switch user {
	case "", "default":
		if len(args) == 0 {
			limaArgs = []string{"shell", name}
		} else {
			limaArgs = append(limaArgs, args...)
		}
	default:
		limaArgs = append(limaArgs, "sudo", "-iu", user)
		limaArgs = append(limaArgs, args...)
	}
	cmd := exec.CommandContext(ctx, p.bin(), limaArgs...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	ui.Detail("interactive shell: limactl %s", strings.Join(limaArgs, " "))
	return cmd.Run()
}

func firstLine(s string) string {
	for _, l := range strings.Split(s, "\n") {
		l = strings.TrimSpace(l)
		if l != "" && !strings.HasPrefix(l, "set -") && !strings.HasPrefix(l, "#") {
			if len(l) > 120 {
				return l[:120] + "..."
			}
			return l
		}
	}
	return "(empty script)"
}

func lastLines(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.TrimSpace(strings.Join(lines, "; "))
}

var _ provider.Provider = (*Provider)(nil)
