apiVersion: v1
kind: Namespace
metadata: {name: dojo-storage-guided}
---
apiVersion: v1
kind: PersistentVolume
metadata: {name: dojo-storage-guided}
spec:
  capacity: {storage: 1Gi}
  accessModes: [ReadWriteOnce]
  storageClassName: dojo-static-guided
  persistentVolumeReclaimPolicy: Delete
  hostPath: {path: /var/lib/dojo/storage-guided, type: DirectoryOrCreate}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: data, namespace: dojo-storage-guided}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: wrong-class
  resources: {requests: {storage: 512Mi}}
