apiVersion: v1
kind: Pod
metadata:
  name: batch
  namespace: dojo-scheduling-guided
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2
  containers:
    - name: batch
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
