apiVersion: v1
kind: Namespace
metadata:
  name: dojo-services-guided
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: dojo-services-guided
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: dojo-services-guided
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: http
