apiVersion: v1
kind: Pod
metadata:
  name: report
  namespace: dojo-scheduling-inspect
spec:
  nodeSelector:
    dojo-tier: special
  containers:
    - name: report
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
